/*
 * Generated by Walle Tools. Do NOT modify.
 */
package com.loit.apps.system.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

import org.hibernate.annotations.GenericGenerator;

import com.loit.core.hibernate.model.BaseModel;
import com.loit.core.hibernate.model.OperationLog;

/**
 * Model class for 岗位
 */
@Entity
@Table(name = "SYS_STATION")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class SysStationModel extends BaseModel implements OperationLog {

	private String stationId;
	private String code;
	private String name;
	private Integer stationTypeId;
	private Integer organizeId;
	private String defaultDispatchFlag;
	private String workDesc;
	private String state;
	private String remarks;
	private String creator;
	private Date createTime;
	private String modifier;
	private Date modifyTime;
	private Integer recVer;

	/**
	 * Get 岗位编码
	 */
	@Column(name = "STATION_ID")
	@Id @GeneratedValue(generator = "UUIDGenerator")
	@GenericGenerator(name="UUIDGenerator", strategy="com.loit.core.hibernate.UUIDGenerator")
	public String getStationId() {
		return stationId;
	}

	/**
	 * Set 岗位编码
	 */
	public void setStationId(String stationId) {
		this.stationId = stationId;
		addValidField("stationId");
	}

	/**
	 * Get 岗位代码
	 */
	@Column(name = "CODE")
	public String getCode() {
		return code;
	}

	/**
	 * Set 岗位代码
	 */
	public void setCode(String code) {
		this.code = code;
		addValidField("code");
	}

	/**
	 * Get 岗位名称
	 */
	@Column(name = "NAME")
	public String getName() {
		return name;
	}

	/**
	 * Set 岗位名称
	 */
	public void setName(String name) {
		this.name = name;
		addValidField("name");
	}

	/**
	 * Get 岗位类型
	 */
	@Column(name = "STATION_TYPE_ID")
	public Integer getStationTypeId() {
		return stationTypeId;
	}

	/**
	 * Set 岗位类型
	 */
	public void setStationTypeId(Integer stationTypeId) {
		this.stationTypeId = stationTypeId;
		addValidField("stationTypeId");
	}

	/**
	 * Get 所属组织
	 */
	@Column(name = "ORGANIZE_ID")
	public Integer getOrganizeId() {
		return organizeId;
	}

	/**
	 * Set 所属组织
	 */
	public void setOrganizeId(Integer organizeId) {
		this.organizeId = organizeId;
		addValidField("organizeId");
	}

	/**
	 * Get 缺省派单标志
	 */
	@Column(name = "DEFAULT_DISPATCH_FLAG")
	public String getDefaultDispatchFlag() {
		return defaultDispatchFlag;
	}

	/**
	 * Set 缺省派单标志
	 */
	public void setDefaultDispatchFlag(String defaultDispatchFlag) {
		this.defaultDispatchFlag = defaultDispatchFlag;
		addValidField("defaultDispatchFlag");
	}

	/**
	 * Get 工作描述
	 */
	@Column(name = "WORK_DESC")
	public String getWorkDesc() {
		return workDesc;
	}

	/**
	 * Set 工作描述
	 */
	public void setWorkDesc(String workDesc) {
		this.workDesc = workDesc;
		addValidField("workDesc");
	}

	/**
	 * Get 状态
	 */
	@Column(name = "STATE")
	public String getState() {
		return state;
	}

	/**
	 * Set 状态
	 */
	public void setState(String state) {
		this.state = state;
		addValidField("state");
	}

	/**
	 * Get 备注
	 */
	@Column(name = "REMARKS")
	public String getRemarks() {
		return remarks;
	}

	/**
	 * Set 备注
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
		addValidField("remarks");
	}

	/**
	 * Get creator
	 */
	@Column(name = "CREATOR")
	public String getCreator() {
		return creator;
	}

	/**
	 * Set creator
	 */
	public void setCreator(String creator) {
		this.creator = creator;
		addValidField("creator");
	}

	/**
	 * Get createTime
	 */
	@Column(name = "CREATE_TIME")
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * Set createTime
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
		addValidField("createTime");
	}

	/**
	 * Get modifier
	 */
	@Column(name = "MODIFIER")
	public String getModifier() {
		return modifier;
	}

	/**
	 * Set modifier
	 */
	public void setModifier(String modifier) {
		this.modifier = modifier;
		addValidField("modifier");
	}

	/**
	 * Get modifyTime
	 */
	@Column(name = "MODIFY_TIME")
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * Set modifyTime
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
		addValidField("modifyTime");
	}

	/**
	 * Get recVer
	 */
	@Column(name = "REC_VER")
	@Version
	public Integer getRecVer() {
		return recVer;
	}

	/**
	 * Set recVer
	 */
	public void setRecVer(Integer recVer) {
		this.recVer = recVer;
		addValidField("recVer");
	}

}
